### ISSUE TITLE
Implement the Transformer model

### ISSUE THREAD

**Issue by JaNoNi** [ml-projects-kiel/OpenCampus-ApplicationofTransformers#9]
Adapt the model proposed here:
https://wandb.ai/wandb/huggingtweets/reports/HuggingTweets-Train-a-Model-to-Generate-Tweets--VmlldzoxMTY5MjI

**Comment by valewer** [comment]
https://www.philschmid.de/fine-tune-a-non-english-gpt-2-model-with-huggingface
